### ISSUE TITLE
Improve RAT Testing Coverage

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/RAT#32]
We need to write tests for the following files, listed in order of importance:

- [x] `RAT.API.RAT` #44
- [x] `RAT.API.RAT_main` #44
- [x] `RAT.API.singleCalculation` #44
- [x] `RAT.targetFunctions.reflectivity_calculation_wrapper` #44
- [x] `RAT.API.RATParseOutToProjectClass` #44
- [x] `RAT.API.RatParseClassToStructs_new` #44
- [x] `RAT.API.parseResulttoStruct` #44
- [x] ~~`RAT.API.outputFcn.ratSendTextOutput`~~ removed in #171
- [x] `RAT.utilities.textProgressBar` #210
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_CustLaycontrast`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_CustLaypoints`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_CustLaysingle`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_XYContrasts`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_XYPoints`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopCppCustlayWrapper.loopCppCustLayWrapper_XYSingle`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.standardTF.standardTF_stanLay.standardTF_stanLay_paraAll`~~ - Routine not called by RAT
- [x] `RAT.targetFunctions.standardTF.standardTF_stanLay.standardTF_stanLay_paraContrasts` #45 
- [x] `RAT.targetFunctions.standardTF.standardTF_stanLay.standardTF_stanLay_paraSingle` #45
- [x] `RAT.targetFunctions.standardTF.standardTF_stanLay.standardTF_stanLay_single` #45
- [x] ~~`RAT.targetFunctions.common.Resolution_Functions.Simple_Gaussian.data_resolution_poly`~~ - Routine removed in #315 
- [x] ~~`RAT.targetFunctions.common.callCustomLayers.call_customLayers`~~ - Routine removed in #116 
- [x] `RAT.targetFunctions.common.callMatlabCustomLayers.callMatlabCustomLayers`  #45
- [x] ~~`RAT.API.outputFcn.ratOutputClass`~~ - Routine removed in #164
- [x] ~~`RAT.API.outputFcn.SpecialEventDataClass`~~ - Routine removed in #164
- [x] ~~`RAT.API.outputFcn.defaultRatOutputFunction`~~ - Routine removed in #164
- [x] `RAT.API.projectClass.contrastsClass` #88
- [x] `RAT.API.projectClass.mergeStructs` #177  

Then, improve test coverage for the following files, listed in order of importance:

- [x] `RAT.API.projectClass.dataClass` #76 
- [x] `RAT.API.projectClass.layersClass_realSLD` #57 
- [x] `RAT.API.projectClass.resolutionsClass` #86  
- [x] `RAT.API.projectClass.customFileClass` #59 
- [x] `RAT.API.projectClass.projectClass` #46 
- [x] `RAT.API.projectClass.backgroundsClass` #94  
- [x] `RAT.API.projectClass.parametersClass` #48 
- [x] `RAT.API.projectClass.multiTypeTable`  #50 
- [x] ~~`RAT.targetFunctions.common.loopMatlabCustomLayers.mexCompile.loopMatlabCustomLayers`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopMatlabCustomLayers.mexCompile.loopMatlabCustomLayers_points`~~ - Routine removed in #116 
- [x] ~~`RAT.targetFunctions.common.loopMatlabCustomLayers.mexCompile.loopMatlabCustomLayers_single`~~ - Routine removed in #116 
- [x] `RAT.API.controlsDef.controlsDef` #52  

Then, the domains class has zero test coverage, but is not called from within RAT:

- [x] ~~`RAT.API.domainsClass.domainsClass`~~ Removed in #84 
- [x] ~~`RAT.API.domainsClass.reflContrastsClass`~~ Removed in #84
- [x] ~~`RAT.API.domainsClass.simContrastsClass`~~ Removed in #84
