### ISSUE TITLE
Implement custom exceptions

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/RAT#69]
A series of RAT custom exceptions have been defined in utilities/exceptions. As we implement tests for the classes in RAT, we should refactor the routines to make use of these custom exceptions, adding additional ones where necessary, using the existing template. The existing custom exceptions are:

`duplicateName, indexOutOfRange, invalidNumberOfInputs, invalidOption, invalidType, invalidValue, nameNotRecognised`

Broadly speaking, this means that lines of code that look like `error(<message>)` should be replaced with
 `throw(<customException>(<message>))`. In `verifyError` tests, we should test for the identifier for each custom exception, given by `<customException>.errorID`

We need to focus on the following classes and their corresponding tests:

- [x] `API/controlsDef/controlsDef.m` #52
- [x] ~~`API/domainsClass/domainsClass.m`~~ Removed in #84 
- [x] ~~`API/domainsClass/reflContrastsClass.m`~~ Removed in #84 
- [x] ~~`API/domainsClass/simContrastsClass.m`~~ Removed in #84 
- [x] `API/projectClass/backgroundsClass.m` #94 
- [x] `API/projectClass/contrastsClass.m` #88 
- [x] `API/projectClass/customFileClass.m` #59 
- [x] `API/projectClass/dataClass.m` #76
- [x] `API/projectClass/layersClassRealSLD.m` #79
- [x] `API/projectClass/multiTypeTable.m` #79
- [x] `API/projectClass/parametersClass.m` #79
- [x] `API/projectClass/projectClass.m` #79
- [x] `API/projectClass/resolutionsClass.m` #86
